doctrine_migrations:
    # List of namespace/path pairs to search for migrations, at least one required
    migrations_paths:
        'App\Migration': 'src/Migration'

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'migration'
            version_column_name: 'version'
            version_column_length: 255

    # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: false

    # Run all migrations in a transaction.
    all_or_nothing: false
