security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    role_hierarchy:
        ROLE_BETA_TESTER:  ROLE_USER
        ROLE_MULTI_PLAYER: ROLE_USER
        ROLE_NEWS_CREATOR: ROLE_USER

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: user_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: profile

            custom_authenticators:
                - App\Security\X509\ClientCertificateAuthenticator
