twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        mastodon_url: '%env(MASTODON_URL)%'

        game_service: '@App\Service\GameService'
        myth_service: '@App\Service\MythService'
        party_service: '@App\Service\PartyService'
        order_service: '@App\Service\OrderService'

when@test:
    twig:
        strict_variables: true
